import '@/app/globals.css';
import type { Metadata } from 'next';
import Header from '@/app/(site)/components/Header';
import Footer from '@/app/(site)/components/Footer';
import ProtectedRoute from '@/components/ProtectedRoute';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ProtectedRoute>
         <div className="h-screen flex flex-col">
          <Header />
          <div className="flex-1 overflow-y-auto pt-16 pb-16 bg-white">
            {children}
          </div>
          <Footer />
        </div>
        </ProtectedRoute>
    </>
  );
}
