import '@/app/globals.css';
import type { Metadata } from 'next';
import Header from '@/app/(site)/components/Header';
import Footer from '@/app/(site)/components/Footer';
import ProtectedRoute from '@/components/ProtectedRoute';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
          <ProtectedRoute>
             <Header />
            <main className="flex-1 pt-16 pb-16 p-6 bg-white">
              {children}
            </main>
            <Footer />
          </ProtectedRoute>
      </body>
    </html>
  );
}
